#!/bin/bash
# ensure-maison-stack.sh - Deploy Maison behind its AppShield gate.
#
# Maison (github.com/Yundera/Maison) is the dashboard that replaces CasaOS: the same
# app grid and the same CasaOS App Store format, in a single Go binary driving the
# Docker socket. It has no file manager, no database, and no authentication of any
# kind — the gate in front of it is the only way in.
#
# Deployed to ${DATA_ROOT}/AppData/maison. The name carries no leading dot, so
# Maison's own managed-app scan (it skips any name containing a dot) picks the stack
# up and the dashboard tiles itself. That is deliberate: it is not hidden.
#
# SECURITY: the compose file never publishes Maison's port — the AppShield gate in
# the same stack is the only route in. Do not "temporarily" add a ports: mapping.
#
# ORDERING: must run AFTER ensure-stack-up.sh. The `pcs` network is owned by the
# mesh stack and joined here as external, and the gate needs auth-registrar / dex
# (mesh stack) reachable by name on it.
#
# Ported from Yundera/template-root; its CasaDash rebrand/legacy-path handling is
# omitted because this template never shipped `casadash`.
set -euo pipefail

# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/library/common.sh"

MAISON_DIR="${DATA_ROOT:-/DATA}/AppData/maison"

# The maison container talks to the Docker socket as a non-root user, so it needs
# the socket's group. Resolve it from the host rather than assuming the usual 999.
if [ ! -S /var/run/docker.sock ]; then
    log_error "/var/run/docker.sock not found; cannot determine DOCKER_GID"
    exit 1
fi
DOCKER_GID="$(stat -c '%g' /var/run/docker.sock)"

# Maison stamps container timezones from TZ. The mesh .env does not carry it.
if [ -f /etc/timezone ]; then
    TZ="$(cat /etc/timezone 2>/dev/null || echo UTC)"
elif [ -L /etc/localtime ]; then
    TZ="$(readlink /etc/localtime | sed 's|.*/zoneinfo/||')"
else
    TZ="UTC"
fi

# --- .env.app: what every app Maison installs receives -----------------------
# The deployment's statement of the world it places apps into: the network they
# join, the domain and public IP their Caddy routes are templated with, the identity
# they seed an admin account from. Maison forwards each key into every app's own
# .env, on install and again on every start — so a box that changes domain or IP
# carries its apps with it instead of stranding them.
#
# It goes in the stack's own directory, which is also Maison's state directory
# (STATE_DIR is left unset, defaulting to DATA_ROOT/AppData/maison). Written BEFORE
# deploy-stack.sh, so a first-ever install finds it already there and never falls
# back to Maison's built-in default — that default is a standalone local install
# (APP_NET=mesh, no domain), and no such network exists here, so every app would
# fail to start.
mkdir -p "$MAISON_DIR"

env_get() { get_env_value "$1"; }

# Temp file + move: Maison reads .env.app from another container, at any moment, to
# start an app — it must never observe a half-written one.
APPENV_TMP="$(mktemp "$MAISON_DIR/.env.app.XXXXXX")"
cat > "$APPENV_TMP" <<EOF
# Generated by ensure-maison-stack.sh from the mesh .env.
# DO NOT EDIT — rewritten on every self-check. Change $ENV_FILE instead.
#
# The variables Maison forwards into every app it manages; see Maison's docs/app-env.md.
APP_NET=pcs
APP_DATA_ROOT=${DATA_ROOT:-/DATA}
APP_DOMAIN=$(env_get DOMAIN)
domain=$(env_get DOMAIN)
APP_PUBLIC_IP=$(env_get PUBLIC_IP)
APP_PUBLIC_IP_DASH=$(env_get PUBLIC_IP_DASH)
APP_PUBLIC_IPV4=$(env_get PUBLIC_IPV4)
APP_PUBLIC_IPV4_DASH=$(env_get PUBLIC_IPV4_DASH)
APP_PUBLIC_IPV6=$(env_get PUBLIC_IPV6)
APP_PUBLIC_IPV6_DASH=$(env_get PUBLIC_IPV6_DASH)
APP_EMAIL=$(env_get EMAIL)
APP_DEFAULT_PASSWORD=$(env_get DEFAULT_PWD)
DefaultUserName=admin
DefaultPassword=$(env_get DEFAULT_PWD)
EOF

# Carries DEFAULT_PWD, exactly as the mesh .env does. Maison runs as root and is
# the only reader.
chmod 600 "$APPENV_TMP"
mv -f "$APPENV_TMP" "$MAISON_DIR/.env.app"
echo "Wrote $MAISON_DIR/.env.app"

exec "$SCRIPTS_DIR/tools/deploy-stack.sh" maison "$MAISON_DIR" \
    "DOCKER_GID=$DOCKER_GID" \
    "TZ=$TZ"
