#!/bin/bash
# ensure-dex.sh - Provision the Dex OIDC broker (the PCS SSO identity provider).
#
# Responsibilities (all idempotent):
#   - generate-once DEX_SESSION_KEY, the session-cookie encryption key,
#   - render Dex config.yaml from the template every run (tracks DOMAIN changes),
#   - append every connector drop-in in connectors.d/ — this script owns NO
#     connector itself; each one is written by the script that owns its issuer
#     (the mesh template's Local Account: ensure-authelia.sh),
#   - own the sqlite data dir so the dex container (uid 1001) can write dex.db,
#   - converge the dex container on the result: ABSENT with no connector (Dex
#     refuses to start with none), otherwise running on the fresh config.
#
# Storage layout (host ${DATA_ROOT}/AppData/auth/ — the auth stack's own folder;
# adopt_auth_state moves dex/ there from the mesh root on a box that predates
# the move):
#   dex/config.yaml          rendered Dex config (re-rendered each run)
#   dex/connectors.d/*.yaml  connector drop-ins, concatenated into config.yaml
#   dex/connector-count      what this script rendered; read by dex_wanted
#   dex/dex.db               Dex sqlite store (clients, codes, refresh tokens, keys)
#   dex/frontend/            rendered login theme (tools/provision-dex-frontend.sh)
#
# RECOVERY / BACKUP: none of this needs backing up — it is all CACHE.
#   - The auth-registrar (mesh-auth) is STATELESS: its OIDC client-secret cache
#     lives inside the container (DEX_CLIENTS_DIR=/tmp/dex-clients), never on a
#     volume. On restart it transparently rotates each client's secret on the
#     next /register.
#   - dex.db is rebuilt automatically on loss. Apps re-register on their next
#     login (the AppShield sidecars hold no persisted creds), and users simply
#     log in again (Dex regenerates its signing keys, invalidating old tokens).
#     Deleting ${DATA_ROOT}/AppData/auth/dex is therefore safe — this script
#     reconstructs config.yaml, the ensure-connector-* scripts rewrite their
#     drop-ins, and the rest self-heals through normal logins.
#   - ONE EXCEPTION: a drop-in that no script owns (one placed by hand, or by a
#     deployment's one-off command) is not regenerated by anything.
#
# Dex is a pure BROKER: it holds no local credential. The local account lives in
# Authelia (see ensure-authelia.sh); the old enablePasswordDB break-glass admin
# is gone, along with the `casaos` connector and the BRIDGE_SECRET it consumed.
#
# NETWORK: Dex's gRPC client-management API is UNAUTHENTICATED, so it is reachable
# only on the isolated `dex-internal` docker network (alias dex-grpc). Only
# auth-registrar sits on that network; app containers (pcs network only) cannot
# reach gRPC.

set -e

# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/library/common.sh"
# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/library/authelia-ready.sh"

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="$SELF_DIR/dex.config.yaml.tmpl"

# Fatal, for the same reason as in ensure-authelia.sh (which normally ran first
# and already did this): never render into an empty folder beside the real state.
adopt_auth_state

DEX_ROOT="$DEX_HOME"
CONFIG_OUT="$DEX_ROOT/config.yaml"

# ghcr.io/dexidp/dex runs as uid/gid 1001 and must own its sqlite tree.
DEX_UID=1001

if [ ! -f "$TEMPLATE" ]; then
    log_error "Dex config template missing at $TEMPLATE"
    exit 1
fi

if [ -z "${DOMAIN:-}" ]; then
    log_error "DOMAIN not set in $ENV_FILE; cannot render Dex config"
    exit 1
fi

mkdir -p "$DEX_ROOT"

# --- session key -------------------------------------------------------------
# `sessions.cookieEncryptionKey` in the template: Dex keeps a real `dex_session`
# cookie (DEX_SESSIONS_ENABLED=true), which is what lets it advertise
# `end_session_endpoint` + back-channel logout, so one logout ends every app.
#
# AES, and Dex accepts ONLY 16, 24 or 32 BYTES — a byte-length limit, not a
# string format: `openssl rand -hex 32` is 64 characters and is rejected. So: 24
# random bytes as base64, exactly 32 ASCII characters, AES-256. Generate-once.
#
# ROTATION invalidates every live Dex session — one round of re-logins across
# every app on the box. Safe at any time. Nothing to back up: a lost key is
# re-minted here.
DEX_SESSION_KEY="$(get_env_value DEX_SESSION_KEY)"
if [ -z "$DEX_SESSION_KEY" ]; then
    DEX_SESSION_KEY="$(openssl rand -base64 24)"
    set_env_value DEX_SESSION_KEY "$DEX_SESSION_KEY"
    log_info "Generated DEX_SESSION_KEY (Dex session cookie encryption)"
fi

# Literal substitution, NOT envsubst: this installer targets arbitrary boxes and
# must not require gettext. It is also the safer of the two here — the values
# below can carry '$' and pass through untouched.
CONTENT="$(cat "$TEMPLATE")"
CONTENT="${CONTENT//\$\{DOMAIN\}/$DOMAIN}"
CONTENT="${CONTENT//\$\{DEX_SESSION_KEY\}/$DEX_SESSION_KEY}"

TMP="$(mktemp "$DEX_ROOT/.config.XXXXXX")"
chmod 600 "$TMP"
printf '%s\n' "$CONTENT" > "$TMP"

# ---------------------------------------------------------------------------
# Connector drop-ins — ${DATA_ROOT}/AppData/auth/dex/connectors.d/*.yaml
#
# The template's `connectors:` key is deliberately left with no items: EVERY
# connector is a drop-in, appended here. Each file holds one or more items for
# the `connectors:` block, indented two spaces to match:
#
#     - type: oidc
#       id: example
#       name: Example
#       config:
#         issuer: https://example-${DOMAIN}
#         ...
#
# Shaped like Authelia's clients.d/*.yml: a deployment federates Dex to something
# this template does not ship without the template knowing anything about it.
# Known writers: ensure-authelia.sh (authelia.yaml, this template),
# Yundera's ensure-connector-yundera.sh (yundera.yaml), the Yundera demo
# (demo-open-entry.yaml).
#
# The directory lives in the runtime data dir, NOT the template tree, so
# ensure-template-sync.sh never touches it and a drop-in survives updates.
# Concatenated onto the freshly-rendered config, which is rewritten from scratch
# each run — so this never accumulates duplicates.
#
# ${DOMAIN} is the only token expanded, letting a drop-in reference the box's
# domain without knowing it at write time. Anything else ($-bearing secrets in
# particular) passes through verbatim.
#
# NOT VALIDATED, deliberately — this runs before Dex sees the file, and a schema
# check here would be a second, drifting copy of Dex's own. Connectors are
# COUNTED, though, by their item lines (`  - `): that count decides whether Dex
# exists at all, so a file holding only comments counts for nothing.
#
# THE COST IS HIGH, so read this before adding one. Dex resolves every oidc
# connector's discovery document AT STARTUP and treats a failure as fatal:
#
#   failed to initialize server: server: Failed to open connector demo:
#   failed to get provider: 502 Bad Gateway
#
# and the process exits. A drop-in pointing at an issuer that is down, slow to
# boot, or not yet routed by Caddy therefore takes down ALL interactive login on
# this box — every other connector included, not just itself. Whatever writes a
# drop-in must confirm the issuer answers over its public URL first, and must
# REMOVE its file rather than leave a stale one behind when it cannot.
# A malformed drop-in does the same thing via a YAML parse error.
#
# Two more rules: keep the shape above, and never reuse a connector id that is
# already taken — `authelia` is the Local Account's, and Dex rejects duplicate
# ids at startup.
# ---------------------------------------------------------------------------
CONNECTOR_COUNT=0
CONNECTORS_D="$DEX_ROOT/connectors.d"
mkdir -p "$CONNECTORS_D"
shopt -s nullglob
for dropin in "$CONNECTORS_D"/*.yaml "$CONNECTORS_D"/*.yml; do
    DROPIN_CONTENT="$(cat "$dropin")"
    DROPIN_CONTENT="${DROPIN_CONTENT//\$\{DOMAIN\}/$DOMAIN}"
    printf '\n%s\n' "$DROPIN_CONTENT" >> "$TMP"
    ITEMS="$(grep -c '^  - ' <<<"$DROPIN_CONTENT" || true)"
    if [ "${ITEMS:-0}" -eq 0 ]; then
        log_warn "Drop-in $(basename "$dropin") declares no connector item (no line starting with '  - ')"
        continue
    fi
    CONNECTOR_COUNT=$((CONNECTOR_COUNT + ITEMS))
    log_info "Added drop-in Dex connector(s) from $(basename "$dropin")"
done
shopt -u nullglob

mv "$TMP" "$CONFIG_OUT"
chmod 600 "$CONFIG_OUT"
echo "Rendered Dex config at $CONFIG_OUT ($CONNECTOR_COUNT connector(s))"

# Recorded for ensure-auth-stack.sh, whose `up` must agree with the decision
# below (dex_wanted, library/common.sh).
printf '%s\n' "$CONNECTOR_COUNT" > "$DEX_CONNECTOR_COUNT_FILE"

# Perms: dex (uid 1001) owns its tree so it can create dex.db. frontend/ inside
# it is provisioned just below and stays root-owned: those files are bind-mounted
# :ro and read as world-readable, so they need no ownership.
chown -R "$DEX_UID:$DEX_UID" "$DEX_ROOT" 2>/dev/null || true
chmod 755 "$DEX_ROOT" 2>/dev/null || true

# Provision the custom login frontend into the dir the compose file bind-mounts
# over the stock image. Copied every run so template updates propagate.
#
# The logic lives in tools/provision-dex-frontend.sh because it is NOT exclusive
# to this script: ensure-auth-stack.sh runs it too, since a `docker compose up`
# that happens before these files exist makes Docker create the file bind-mount
# sources as DIRECTORIES and permanently breaks `dex`. See that tool's header.
"$SCRIPTS_DIR/tools/provision-dex-frontend.sh" \
    || log_warn "Dex frontend provisioning reported an error"

# ---------------------------------------------------------------------------
# Converge the container on what was just rendered.
#
# NO CONNECTOR: Dex cannot start ("server: no connectors specified"), so it must
# not exist (see dex_wanted, library/common.sh). The normal state of an unclaimed
# box with no drop-in — every gate shows its "sign-in unavailable" page meanwhile.
#
# AT LEAST ONE: a running Dex is restarted to pick up the new config (a mounted
# file change does not trigger a compose recreate) — unless it is still bound to
# the pre-move directory, see restart_if_bound. An absent or stopped one is
# STARTED, through compose so it is created exactly as the stack defines it; that
# is the path a claim, an onboarding or a new drop-in takes out of the empty
# state. Before the auth stack has ever been deployed (a fresh install, where this
# runs ahead of ensure-auth-stack.sh) there is nothing to start: the deploy brings
# Dex up itself.
# ---------------------------------------------------------------------------
if [ "$CONNECTOR_COUNT" -eq 0 ]; then
    log_warn "Dex has NO connector — interactive login is impossible on this box, so Dex is kept absent."
    log_warn "  Cause: the local account is unclaimed and no drop-in connector is present."
    log_warn "  Fix over SSH: $SCRIPTS_DIR/tools/authelia-user-manager.sh claim <username>"
    if docker container inspect dex >/dev/null 2>&1; then
        docker rm -f dex >/dev/null 2>&1 \
            && echo "Removed the dex container (no connector to serve)" \
            || log_warn "Could not remove the dex container"
    fi
elif [ "$(docker container inspect -f '{{.State.Running}}' dex 2>/dev/null)" = "true" ]; then
    restart_if_bound dex "$DEX_ROOT" || true
elif [ -f "$AUTH_STACK_DIR/docker-compose.yml" ]; then
    # DEX MUST NOT START BEFORE AUTHELIA ANSWERS when Local Account is among its
    # connectors (ensure-auth-stack.sh has the long version).
    if [ "$(docker container inspect -f '{{.State.Running}}' authelia 2>/dev/null)" = "true" ]; then
        wait_for_authelia
    fi
    echo "Starting dex ($CONNECTOR_COUNT connector(s))"
    docker compose --project-directory "$AUTH_STACK_DIR" -f "$AUTH_STACK_DIR/docker-compose.yml" \
        up -d --quiet-pull --no-deps dex \
        || log_warn "Could not start dex; the next ensure-auth-stack.sh run brings it up"
else
    echo "The auth stack is not deployed yet; ensure-auth-stack.sh brings dex up"
fi

echo "Dex provisioning complete (data root: $DEX_ROOT)"
